### ISSUE TITLE
Playbook fails due to run with Ansible 2.10

### ISSUE THREAD

**Issue by douglas-vaz** [GoogleCloudPlatform/google-cloud-ops-agents-ansible#88]
Ansible version: 2.10
OS: Ubuntu 20.04
Ansible role using Galaxy

Playbook:
```
---
- hosts: all
  become: true
  roles:
    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent
```

Error:
```
ERROR! couldn't resolve module/action 'win_shell'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/root/.ansible/roles/googlecloudplatform.google_cloud_ops_agents/handlers/main.yml': line 8, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: "restart windows {{ agent_type }} agent"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:
    with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"
 ```
